project:
  type: website

website:
  title: "Mounika"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Stories
        href: stories/index.qmd
      - text: Projects
        href: projects/index.qmd
      - text: Blog
        href: blog/index.qmd
  search: true

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
